agents/urls.py
from django.urls import path
from . import views



app_name = 'agents'

urlpatterns = [
    path('agents/', views.AgentListView.as_view(), name="agents"),
    path('agents/add/', views.AgentCreateView.as_view(), name="agent_create"),
    path('agents/details/<int:pk>/', views.AgentDetailView.as_view(), name="agent_details"),
    path('agents/update/<int:pk>/', views.AgentUpdateView.as_view(), name="agent_update"),
    path('agents/delete/<int:pk>/', views.AgentDeleteView.as_view(), name="agent_delete"),
]
    

crmz/urls.py
from django.contrib import admin
from django.urls import path, include
from leads.views import RegistrationView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)



urlpatterns = [
    path('admin/', admin.site.urls),

    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegistrationView.as_view(), name='register'),

    # Password reset flow
    path('reset_password/', PasswordResetView.as_view(), name='password_reset'),
    path('reset_password_done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('', include('leads.urls', namespace='leads')),
    path('', include('agents.urls', namespace='agents')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT) 
    
    

agents/models.py
from django.db import models

agents/forms.py
from django import forms
from django.contrib.auth import get_user_model


User = get_user_model()



class AgentCreationForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'email',
            'username',
            'first_name',
            'last_name',
            )

agents/views.py
from django.shortcuts import render, reverse
# from django.contrib.auth.mixins import LoginRequiredMixin
from .mixins import OrganizerAndLoginRequiredMixin
from django.views import generic
from leads.models import Agent
from . import forms
from django.core.mail import send_mail
import random



class AgentListView(OrganizerAndLoginRequiredMixin, generic.ListView):
    template_name = "agents/agent_list.html"
    context_object_name = 'agents'
    
    def get_queryset(self):
        organization = self.request.user.userprofile
        return Agent.objects.filter(organization=organization)
    

class AgentCreateView(OrganizerAndLoginRequiredMixin, generic.CreateView):
    template_name = "agents/agent_create.html"
    form_class= forms.AgentCreationForm

    def get_success_url(self):
        return reverse('agents:agents')
    
    def form_valid(self, form):
        user = form.save(commit = False)
        user.is_agent = True
        user.is_organizer = False
        user.set_password(f"{random.randint(0, 100000)}")
        user.save()
        
        Agent.objects.create(
            user = user,
            organization = self.request.user.userprofile,
        )
        
        send_mail(
            subject= "You were added as an agent.",
            message= "Please visit our site and start working",
            from_email= "admin@mail.com",
            recipient_list=[user.email]
        )
        
        return super(AgentCreateView, self).form_valid(form)
    

class AgentDetailView(OrganizerAndLoginRequiredMixin, generic.DetailView):
    template_name = "agents/agent_details.html"
    context_object_name = 'agent'
    
    def get_queryset(self):
        organization = self.request.user.userprofile
        return Agent.objects.filter(organization=organization)
    
class AgentUpdateView(OrganizerAndLoginRequiredMixin, generic.UpdateView):
    template_name = "agents/agent_update.html"
    context_object_name = 'agent'
    form_class = forms.AgentCreationForm
    
    def get_queryset(self):
        return Agent.objects.filter(organization= self.request.user.userprofile)
    
    def get_success_url(self):
        return reverse('agents:agent_details', kwargs={"pk": self.object.pk})
    
class AgentDeleteView(OrganizerAndLoginRequiredMixin, generic.DeleteView):
    template_name = "agents/agent_delete.html"
    context_object_name = 'agent'
    
    def get_queryset(self):
        organization = self.request.user.userprofile
        return Agent.objects.filter(organization=organization)
    
    
    def get_success_url(self):
        return reverse('agents:agents')

agents/templates/agents/agent_create.html
{% extends "base.html" %}

{% block content %}
{% load tailwind_filters %}

<a href="/">Back to home</a>

<hr>
<div class="flex items-center flex-col">
    <form action="{% url 'agents:agent_create' %}" method="post" class="w-full max-w-[500px]">
        {% csrf_token %}
        <h1 class='text-4xl text-gray-800'>Create a new agent</h1>

        <br>

        {{ form|crispy }}

        <button type="submit" class="flex ml-auto text-white bg-blue-500 border-0 py-2 px-6 focus:outline-none hover:bg-blue-600 rounded mb-2">Save</button>
    </form>
</div>



{% endblock  %}

agents/templates/agents/agent_delete.html
{% extends "base.html" %}

{% block content %}

<form action="{% url 'agents:agent_delete' agent.pk %}" method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete this agent?</p>
    <br>

    <div class="mt-4 flex gap-4">
        <button type="submit"
                class="bg-red-500 text-white px-4 py-2 rounded hover:bg-red-600">
            Delete
        </button>

        <a href="{% url 'agents:agent_details' agent.pk %}"
           class="bg-gray-200 px-4 py-2 rounded hover:bg-gray-300">
            Cancel
        </a>
    </div>
</form>


{% endblock  %}

agents/templates/agents/agent_details.html
{% extends "base.html" %}

{% block content %}


<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h2 class="text-sm title-font text-gray-500 tracking-widest">Agent</h2>
            <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ agent.user.username }}</h1>
            <div class="w-full max-w-[400px] aspect-square mb-6">
                <img
                    alt="Lead image"
                    src="https://dummyimage.com/400x400"
                    class="w-full h-full object-cover object-center rounded"
                >
            </div>

        <div class="flex mb-4">
          <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Description</a>
        </div>
        <p class="leading-relaxed mb-4">Fam locavore kickstarter distillery. Mixtape chillwave tumeric sriracha taximy chia microdosing tilde DIY. XOXO fam inxigo juiceramps cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.</p>
        <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">Email</span>
            <span class="ml-auto text-gray-900">{{ agent }}</span>
        </div>
        <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">Age</span>
            <span class="ml-auto text-gray-900">{{ lead.age }}</span>
        </div>
        <div class="flex border-t border-b mb-6 border-gray-200 py-2">
          <span class="text-gray-500">Phone</span>
          <span class="ml-auto text-gray-900">+ 013 XXX XXXX</span>
        </div>
        <div class="flex">
            <a href="{% url 'agents:agent_update' agent.pk %}" class="flex ml-auto text-white bg-blue-500 border-0 py-2 px-6 focus:outline-none hover:bg-blue-600 rounded">Update</a>
             <a href="{% url 'agents:agent_delete' agent.pk %}" class="text-white bg-red-500 border-0 py-2 px-6 inline-flex items-center justify-center ml-4 hover:bg-red-600 rounded">Delete</a>
        </div>
      </div>
    </div>
  </div>
</section>


{% endblock  %}

agents/templates/agents/agent_list.html
{% extends "base.html" %}

{% block content %}
<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
    <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">

        <div>
            <h1 class='text-4xl text-gray-800'>Agents</h1>
        </div>

        <div>
            <a href="{% url 'agents:agent_create' %}" class="flex ml-auto text-white bg-blue-500 border-0 py-2 px-6 focus:outline-none hover:bg-blue-600 rounded mb-2">Add new Agent</a>
        </div>

    </div>
    <div class="flex flex-wrap -m-4">
    {% for agent in agents %}
    <div class="p-4 lg:w-1/2 md:w-full">
        <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
            <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
                    <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                </svg>
            </div>
            <div class="flex-grow">
                <h2 class="text-gray-900 text-lg title-font font-medium mb-3">{{ agent.user.username }}</h2>
                <p class="leading-relaxed text-base">Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub indxgo juice poutine.</p>
                <a href="{% url 'agents:agent_details' agent.pk %}" class="mt-3 text-indigo-500 inline-flex items-center">See More...
                    <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                        <path d="M5 12h14M12 5l7 7-7 7"></path>
                    </svg>
                </a>
            </div>
        </div>
    </div>
    {% endfor %}
    </div>
  </div>
</section>
{% endblock  %}

agents/templates/agents/agent_update.html
{% extends "base.html" %}

{% block content %}
{% load tailwind_filters %}
<div class="flex items-center flex-col"> 
    
    <form action="{% url 'agents:agent_update' agent.pk %}" method="post" class="w-full max-w-[500px]">
        {% csrf_token %}
        <h1 class='text-4xl text-gray-800'>Update Agent details</h1>
        
        <br>
        
        {{ form|crispy }}
        
        <button type="submit" class="flex ml-auto text-white bg-blue-500 border-0 py-2 px-6 focus:outline-none hover:bg-blue-600 rounded mb-2">Update</button>
    </form>
</div>


{% endblock  %}