agents/urls.py
from django.urls import path
from . import views



app_name = 'agents'

urlpatterns = [
    path('agents/', views.AgentListView.as_view(), name="agents"),
    path('agents/add/', views.AgentCreateView.as_view(), name="agent_create"),
    path('agents/details/<int:pk>/', views.AgentDetailView.as_view(), name="agent_details"),
    path('agents/update/<int:pk>/', views.AgentUpdateView.as_view(), name="agent_update"),
    path('agents/delete/<int:pk>/', views.AgentDeleteView.as_view(), name="agent_delete"),
]
    

crmz/urls.py
from django.contrib import admin
from django.urls import path, include
from leads.views import RegistrationView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)



urlpatterns = [
    path('admin/', admin.site.urls),

    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegistrationView.as_view(), name='register'),

    # Password reset flow
    path('reset_password/', PasswordResetView.as_view(), name='password_reset'),
    path('reset_password_done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('', include('leads.urls', namespace='leads')),
    path('', include('agents.urls', namespace='agents')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT) 
    
    

leads/urls.py
from django.urls import path
from . import views

app_name = 'leads'

""" urlpatterns = [
    path('', views.home_page, name="home_page"),
    path('leads/', views.lead_list, name="lead_list"),
    path('leads/details/<int:pk>/', views.lead_details, name="lead_details"),
    path('leads/add/', views.lead_create, name="lead_create"),
    path('leads/update/<int:pk>/', views.lead_update, name="lead_update"),
    path('leads/delete/<int:pk>/', views.lead_delete, name="lead_delete"),
] """


urlpatterns = [
    path('', views.HomeView.as_view(), name="home_page"),
    path('leads/', views.LeadListView.as_view(), name="lead_list"),
    path('leads/details/<int:pk>/', views.LeadDetailView.as_view(), name="lead_details"),
    path('leads/add/', views.LeadCreateView.as_view(), name="lead_create"),
    path('leads/update/<int:pk>/', views.LeadUpdateView.as_view(), name="lead_update"),
    path('leads/delete/<int:pk>/', views.LeadDeleteView.as_view(), name="lead_delete"),
    path('leads/assign_agent/<int:pk>/', views.AgentAssignView.as_view(), name="assign_agent"),
    path('leads/categories/', views.CategoryListView.as_view(), name="categories"),
    path('leads/categories/details/<int:pk>/', views.CategoryDetailView.as_view(), name="category_details"),
    path('leads/categories/update/<int:pk>/', views.LeadCategoryUpdateView.as_view(), name="category_update"),
]



    

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} CRM {% endblock  %}</title>
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
    <script src="{% static '/js/main.js' %}"></script>
  </head>
</head>
<body>
    <div class="max-w-7xl mx-auto bg-gray-100">
        {% include "header.html" %}
        {% block content %}{% endblock  %}
    </div>
</body>
</html>

templates/footer.html
<footer class="text-gray-600 body-font">
  <div class="container px-5 py-8 mx-auto flex items-center sm:flex-row flex-col">
    <a class="flex title-font font-medium items-center md:justify-start justify-center text-gray-900">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
        <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
      </svg>
      <span class="ml-3 text-xl">Tailblocks</span>
    </a>
    <p class="text-sm text-gray-500 sm:ml-4 sm:pl-4 sm:border-l-2 sm:border-gray-200 sm:py-2 sm:mt-0 mt-4">© 2020 Tailblocks —
      <a href="https://twitter.com/knyttneve" class="text-gray-600 ml-1" rel="noopener noreferrer" target="_blank">@knyttneve</a>
    </p>
    <span class="inline-flex sm:ml-auto sm:mt-0 mt-4 justify-center sm:justify-start">
      <a class="text-gray-500">
        <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
          <path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"></path>
        </svg>
      </a>
      <a class="ml-3 text-gray-500">
        <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
          <path d="M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z"></path>
        </svg>
      </a>
      <a class="ml-3 text-gray-500">
        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
          <rect width="20" height="20" x="2" y="2" rx="5" ry="5"></rect>
          <path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37zm1.5-4.87h.01"></path>
        </svg>
      </a>
      <a class="ml-3 text-gray-500">
        <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="0" class="w-5 h-5" viewBox="0 0 24 24">
          <path stroke="none" d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z"></path>
          <circle cx="4" cy="4" r="2" stroke="none"></circle>
        </svg>
      </a>
    </span>
  </div>
</footer>

templates/header.html
<header class="text-gray-600 body-font shadow-sm">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">

    <!-- Logo -->
    <a href="{% url 'leads:home_page' %}"
       class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">

      <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor"
           stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
           class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full"
           viewBox="0 0 24 24">
        <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
      </svg>

      <span class="ml-3 text-xl">CMS</span>
    </a>

    <!-- Navigation -->
    <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center gap-3">

      <a href="{% url 'leads:home_page' %}"
         class="px-4 py-2 rounded-md text-gray-700 bg-gray-100 
                hover:bg-indigo-100 hover:text-indigo-600 
                transition">
        Home
      </a>

      {% if request.user.is_organizer %}
      <a href="{% url 'agents:agents' %}"
        class="px-4 py-2 rounded-md text-gray-700 bg-gray-100 
        hover:bg-indigo-100 hover:text-indigo-600 
        transition">
        Agents
      </a>
      {% endif %}
      
      <a href="{% url 'leads:lead_list' %}"
         class="px-4 py-2 rounded-md text-gray-700 bg-gray-100 
                hover:bg-indigo-100 hover:text-indigo-600 
                transition">
        Leads
      </a>

      {% if not request.user.is_authenticated %}  
        <a href="{% url 'register' %}"
          class="px-4 py-2 rounded-md text-gray-700 bg-gray-100 
          hover:bg-indigo-100 hover:text-indigo-600 
          transition">
          Register
        </a>
      {% endif %}

    </nav>

    {% if request.user.is_authenticated %}
    
    <!-- Logout Button -->
    <form method="post" action="{% url 'logout' %}" class="ml-4">
        {% csrf_token %}
        <button type="submit"
            class="inline-flex items-center bg-indigo-500 text-white 
            px-4 py-2 rounded-md shadow 
            hover:bg-indigo-600 transition">
            
            Logout

            <svg fill="none" stroke="currentColor" stroke-linecap="round"
            stroke-linejoin="round" stroke-width="2"
            class="w-4 h-4 ml-1" viewBox="0 0 24 24">
              <path d="M5 12h14M12 5l7 7-7 7"></path>
            </svg>
        </button>
    </form>

    {% else %}

    <!-- Login Button -->
    <a href="{% url 'login' %}"
        class="ml-4 inline-flex items-center bg-indigo-500 text-white 
        px-4 py-2 rounded-md shadow 
        hover:bg-indigo-600 transition 
        mt-4 md:mt-0">
        
        Login
        
        <svg fill="none" stroke="currentColor" stroke-linecap="round"
        stroke-linejoin="round" stroke-width="2"
        class="w-4 h-4 ml-1" viewBox="0 0 24 24">
        <path d="M5 12h14M12 5l7 7-7 7"></path>
      </svg>
    </a>
    
    {% endif %}

  </div>
</header>